# Agregar su credenciales de mongo atlas

spring:
  data:
    mongodb:
      database: db_ms_product
      uri: mongodb+srv://Renato:1234@cluster0.8l8iw.mongodb.net/db_ms_product?retryWrites=true&w=majority

server :
  port : 8082